# Generated by Django 2.1 on 2018-10-24 19:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permis_chauffeur', models.CharField(max_length=32, unique=True, verbose_name=' Numero de Permis')),
                ('type_permis', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Grand Taxi'), ('2', 'Petit Taxi')], max_length=3, verbose_name='Type de permis')),
                ('nom_chauffeur', models.CharField(max_length=128, verbose_name='Nom')),
                ('sexe_chauffeur', models.CharField(choices=[('F', 'FEMININ'), ('M', 'MASCULIN'), ('I', 'INDETERMINE')], max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('cin_chauffeur', models.CharField(max_length=32, unique=True, verbose_name='CIN')),
                ('visite_medicale', models.DateField(verbose_name='Date de visite Medicale')),
                ('num_telephone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Numero Telephone')),
                ('isActive', models.BooleanField(default=True, verbose_name='Activé')),
                ('isPrivate', models.BooleanField(default=False, verbose_name='Privé')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.CharField(default='000000', editable=False, max_length=20, unique=True)),
                ('date_permission', models.DateField(verbose_name='Date de permission')),
                ('destination', models.CharField(blank=True, max_length=128, null=True, verbose_name='Destination')),
                ('duree_permission', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9)], verbose_name='Durée de permission')),
                ('periode_permission', models.CharField(blank=True, choices=[('Ma', 'Matin'), ('So', 'Soir')], max_length=2, null=True, verbose_name='Periode de permission')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permissions.Chauffeur', verbose_name='Chauffeur')),
            ],
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_taxi', models.CharField(max_length=32, verbose_name='Numero Taxi')),
                ('type_taxi', models.CharField(choices=[('1', 'Grand Taxi'), ('2', 'Petit Taxi')], max_length=1, verbose_name='Type Taxi')),
                ('matricule', models.CharField(max_length=32, verbose_name='Matricule')),
                ('agrement', models.CharField(max_length=32, verbose_name='Agrement')),
                ('Marque', models.CharField(max_length=128, verbose_name='Marque de vehicule')),
                ('modele', models.CharField(max_length=128, verbose_name='Modele de vehicule')),
                ('assurance', models.DateField(verbose_name="Date d'assurance")),
                ('vite_technique', models.DateField(verbose_name='Date de Visite technique')),
                ('isActive', models.BooleanField(default=True, verbose_name='Activé')),
                ('isPrivate', models.BooleanField(default=False, verbose_name='Privé')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='taxi',
            unique_together={('numero_taxi', 'type_taxi')},
        ),
        migrations.AddField(
            model_name='permission',
            name='taxi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permissions.Taxi', verbose_name='Taxi'),
        ),
    ]
