# Generated by Django 2.1 on 2018-11-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='sexe_chauffeur',
            field=models.CharField(choices=[('F', 'FEMININ'), ('M', 'MASCULIN'), ('I', 'INDETERMINE')], default='M', max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='agrement',
            field=models.CharField(max_length=32, unique=True, verbose_name='Agrement'),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='matricule',
            field=models.CharField(max_length=32, unique=True, verbose_name='Matricule'),
        ),
    ]
