# Generated by Django 2.1 on 2018-10-20 11:33

from django.db import migrations, models
import permissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permission_id',
            field=models.CharField(default=permissions.models.foo, editable=False, max_length=20, unique=True),
        ),
    ]
