# Generated by Django 2.1 on 2018-11-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_auto_20181111_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxi',
            old_name='vite_technique',
            new_name='visite_technique',
        ),
    ]
